/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProtectedModulesRouteImport } from './routes/_protected/modules'
import { Route as ProtectedPlanosIndexRouteImport } from './routes/_protected/planos/index'
import { Route as ProtectedPlanosStudyIdRouteImport } from './routes/_protected/planos/$studyId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedModulesRoute = ProtectedModulesRouteImport.update({
  id: '/modules',
  path: '/modules',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedPlanosIndexRoute = ProtectedPlanosIndexRouteImport.update({
  id: '/planos/',
  path: '/planos/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedPlanosStudyIdRoute = ProtectedPlanosStudyIdRouteImport.update({
  id: '/planos/$studyId',
  path: '/planos/$studyId',
  getParentRoute: () => ProtectedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/modules': typeof ProtectedModulesRoute
  '/planos/$studyId': typeof ProtectedPlanosStudyIdRoute
  '/planos': typeof ProtectedPlanosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/modules': typeof ProtectedModulesRoute
  '/planos/$studyId': typeof ProtectedPlanosStudyIdRoute
  '/planos': typeof ProtectedPlanosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/_protected/modules': typeof ProtectedModulesRoute
  '/_protected/planos/$studyId': typeof ProtectedPlanosStudyIdRoute
  '/_protected/planos/': typeof ProtectedPlanosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/modules'
    | '/planos/$studyId'
    | '/planos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/modules'
    | '/planos/$studyId'
    | '/planos'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/dashboard'
    | '/login'
    | '/_protected/modules'
    | '/_protected/planos/$studyId'
    | '/_protected/planos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRoute: typeof ProtectedRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/modules': {
      id: '/_protected/modules'
      path: '/modules'
      fullPath: '/modules'
      preLoaderRoute: typeof ProtectedModulesRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/planos/': {
      id: '/_protected/planos/'
      path: '/planos'
      fullPath: '/planos'
      preLoaderRoute: typeof ProtectedPlanosIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/planos/$studyId': {
      id: '/_protected/planos/$studyId'
      path: '/planos/$studyId'
      fullPath: '/planos/$studyId'
      preLoaderRoute: typeof ProtectedPlanosStudyIdRouteImport
      parentRoute: typeof ProtectedRoute
    }
  }
}

interface ProtectedRouteChildren {
  ProtectedModulesRoute: typeof ProtectedModulesRoute
  ProtectedPlanosStudyIdRoute: typeof ProtectedPlanosStudyIdRoute
  ProtectedPlanosIndexRoute: typeof ProtectedPlanosIndexRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedModulesRoute: ProtectedModulesRoute,
  ProtectedPlanosStudyIdRoute: ProtectedPlanosStudyIdRoute,
  ProtectedPlanosIndexRoute: ProtectedPlanosIndexRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRoute: ProtectedRouteWithChildren,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
